apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-state
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Recycle"
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pvsts/