apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-deployment-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Recycle"
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/