apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: petya
  namespace: default
subjects:
- kind: ServiceAccount
  name: petya
  namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io