apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
kind: ClusterRoleBinding
metadata:
  name: deploy_edit_user
  # namespace: default
  # the default namespace (applicable to RoleBinding) is default
subjects:
- kind: User
  name: deploy_edit_user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy-edit
  apiGroup: rbac.authorization.k8s.io